CREATE TABLE Academy (
	id	INTEGER NOT NULL UNIQUE,
	name	TEXT,
	address	TEXT,
	call	TEXT,
	kind_of_academy	TEXT,
	type	TEXT,
	affiliation	TEXT,
	process	TEXT,
	lecture	TEXT,
	people	INTEGER,
	duration	TEXT,
	time	INTEGER,
	teaching_price	INTEGER,
	test_price	INTEGER,
	material_price	INTEGER,
	meal_price	INTEGER,
	dorm_price	INTEGER,
	car_price	INTEGER,
	clothing_price	INTEGER,
	etc_price	INTEGER,
	total_price	INTEGER,
	Fname	TEXT,
	teacher	INTEGER,
	PRIMARY KEY(id)
)